FROM bamcis/ca-alpine:1.0.0

MAINTAINER Michael Haken michael.haken@outlook.com

# Protobuf 2.5.0 (exactly this version) is required to build hadoop
ARG PROTOBUF_VERSION=2.5.0
ARG GOOGLETEST_VERSION=1.5.0    

#
# Build protobuf library
#
RUN apk --no-cache add --virtual .builddeps \
        autoconf \
        automake \
        build-base \
		curl \
        libtool \
        zlib-dev \
	&& mkdir -p /tmp/protobuf-src \
	&& mkdir -p /tmp/protobuf-src/gtest \
    && wget -qO- https://github.com/google/protobuf/archive/v${PROTOBUF_VERSION}.tar.gz \
    | tar -xz -f - --directory /tmp/protobuf-src --strip 1 \
    && cd /tmp/protobuf-src \
    # Get google unit tests
    && wget -q -O - https://github.com/google/googletest/archive/release-${GOOGLETEST_VERSION}.tar.gz \
    | tar -xz -f - --directory /tmp/protobuf-src/gtest --strip 1 \
    # Build the protobuf code
    && ./autogen.sh \
    && CXXFLAGS="$CXXFLAGS -fno-delete-null-pointer-checks" ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var \
    && make \
    && make check \
    && make install \
	&& protoc --version \
	&& cd / \
    && rm -rf /tmp/protobuf-src \
	&& apk del .builddeps